version: '3.3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/challenge
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  db:
    image: bitnami/postgresql:15
    environment:
      - POSTGRESQL_DATABASE=challenge
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/bitnami/postgresql

volumes:
  postgres-data: