challenge:
  config:

    jwt:
      secret: '957386928648455625d236456sdf66645566466236d4fsg6984566354456546f'
      expirationTimeInMinutes: 24

    admin-user:
      create: true
      username: 'townsq_super'
      password: 'verySecurePassword'

spring:

  datasource:
    url: jdbc:postgresql://db:5432/challenge
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update